title: Coral Bleaching - BIOL 417
author: Kaede Ito
execute:
  execute_notebooks: cache
  allow_errors: true

exclude_patterns:
  - .venv/*
  - extra_docs/*

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
- references.bib
sphinx:
  extra_extensions:
  - sphinxcontrib.drawio
  recursive_update: true
  config:
    bibtex_reference_style: author_year

html:
  use_repository_button: true

repository:
  url: https://github.com/Mapleia/BIOL417_Coral
  branch: main